RESUME_UPLOADED_TOPIC = "resume.uploaded"
RESUME_PARSED_TOPIC = "resume.parsed"
RESUME_EMBEDDED_TOPIC = "resume.embedded"
CANDIDATE_RANKED_TOPIC = "candidate.ranked"


ALL_TOPICS = (
    RESUME_UPLOADED_TOPIC,
    RESUME_PARSED_TOPIC,
    RESUME_EMBEDDED_TOPIC,
    CANDIDATE_RANKED_TOPIC,
)
